apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark-devereux-sit323-prac7p
  labels:
    app: calculator-microservice-app
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: calculator-microservice-app
      tier: frontend
  template:
    metadata:
      labels:
        app: calculator-microservice-app
        tier: frontend
    spec:
      containers:
      - name: sit323-prac7p-kubernetes
        image: markdevereux/calculator-microservice-app
        ports:
        - containerPort: 8080