version: '3.0'

services:
  #multiple microservices can be added under "services" 
  app:
    #image: markdevereux/node-web-app:latest
    # The build context 
    build: .
    volumes:
      - .:/usr/src/app
    container_name: Prac-5p
    restart: unless-stopped
      # Specifies the dockerfile building the image
      #dockerfile: Dockerfile
    # Mapping the ports of the container and host computer 
    ports:
      - "8080:8080"
    command: bash -c /usr/src/app/start.sh
    env_file: .env
  
  #second microservice - database
  #mysqldb:
  #image:
  #restart:
  #env_file:
  #environment:
  #ports:
  #volumes: