#Specifies the version of docker compose file format to use
version: '1'

# Start of definition of service
services:
  # The name of the service
  calculator-microservice-app:
    container_name: calculator-microservice-app
    image: markdevereux/calculator-microservice-app
    # The build context 
    build:
      context: .
      # Specifies the dockerfile building the image
      dockerfile: Dockerfile
    # Mapping the ports of the container and host computer 
    ports:
      - "8080:8080"